-- ============================================================
-- Phase 2 Migration: Addresses, Email Drafts, SMS, Digest
-- Run in Supabase SQL Editor
-- ============================================================

-- ----------------------------------------
-- LEAD ADDRESSES
-- Multiple addresses per lead (properties, etc.)
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS lead_addresses (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id        UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  label          TEXT NOT NULL DEFAULT 'Property',  -- e.g. "Vacation Home", "Investment Property"
  street         TEXT,
  city           TEXT,
  state          TEXT DEFAULT 'FL',
  zip            TEXT,
  notes          TEXT,
  is_primary     BOOLEAN NOT NULL DEFAULT false,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS lead_addresses_lead_id_idx ON lead_addresses(lead_id);

-- Ensure only one primary address per lead
CREATE UNIQUE INDEX IF NOT EXISTS lead_addresses_primary_idx
  ON lead_addresses(lead_id)
  WHERE is_primary = true;

-- ----------------------------------------
-- EMAIL DRAFTS
-- AI-generated drafts waiting for rep review/send
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS email_drafts (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id          UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  to_email         TEXT NOT NULL,
  to_name          TEXT,
  subject          TEXT NOT NULL,
  body             TEXT NOT NULL,       -- plain text, editable
  trigger_type     TEXT,                -- 'follow_up_due' | 'stage_change' | 'manual' | 'sequence'
  trigger_context  JSONB,               -- raw context used to generate the draft
  status           TEXT NOT NULL DEFAULT 'pending',  -- pending | sent | dismissed
  ai_generated     BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at          TIMESTAMPTZ,
  sent_by          UUID REFERENCES profiles(id),
  dismissed_at     TIMESTAMPTZ,
  dismissed_by     UUID REFERENCES profiles(id)
);

CREATE INDEX IF NOT EXISTS email_drafts_lead_id_idx ON email_drafts(lead_id);
CREATE INDEX IF NOT EXISTS email_drafts_status_idx ON email_drafts(status);

-- ----------------------------------------
-- SMS MESSAGES
-- Log of all outbound (and future inbound) SMS
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS sms_messages (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id      UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  to_phone     TEXT NOT NULL,
  body         TEXT NOT NULL,
  status       TEXT NOT NULL DEFAULT 'pending',   -- pending | sent | delivered | failed
  twilio_sid   TEXT,
  direction    TEXT NOT NULL DEFAULT 'outbound',  -- outbound | inbound
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at      TIMESTAMPTZ,
  created_by   UUID REFERENCES profiles(id)
);

CREATE INDEX IF NOT EXISTS sms_messages_lead_id_idx ON sms_messages(lead_id);

-- ----------------------------------------
-- DAILY DIGESTS
-- One digest per day per role, generated by AI
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS daily_digests (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  digest_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  digest_type    TEXT NOT NULL DEFAULT 'sales_rep',  -- sales_rep | owner
  content        JSONB NOT NULL,                     -- structured digest payload
  generated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(digest_date, digest_type)
);

-- ----------------------------------------
-- RLS POLICIES
-- ----------------------------------------

ALTER TABLE lead_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_digests ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read/write all rows (single-tenant for now)
CREATE POLICY "auth_all_lead_addresses" ON lead_addresses
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth_all_email_drafts" ON email_drafts
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth_all_sms_messages" ON sms_messages
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "auth_all_daily_digests" ON daily_digests
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ----------------------------------------
-- UPDATED_AT TRIGGERS
-- ----------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER lead_addresses_updated_at
  BEFORE UPDATE ON lead_addresses
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER email_drafts_updated_at
  BEFORE UPDATE ON email_drafts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
